# initialize vars from env


postgres_user: "{{ lookup('env', 'POSTGRES_USER') }}"
postgres_db: "{{ lookup('env', 'POSTGRES_DB') }}"
postgres_table: "{{ lookup('env', 'POSTGRES_TABLE') }}"
db_password: "{{ lookup('env', 'POSTGRES_PASS') }}"


rabbitmq_user: "{{ lookup('env', 'RABBITMQ_USER') }}"
rabbitmq_password: "{{ lookup('env', 'RABBITMQ_PASS') }}"
rabbitmq_queue: "{{ lookup('env', 'RABBITMQ_QUEUE') }}"


redis_password: "{{ lookup('env', 'REDIS_PASSWORD') }}"


secret_key: "{{ lookup('env', 'SECRET_KEY') }}"

rds_endpoint: "{{ lookup('env', 'RDS_ENDPOINT')}}"