- name: download k3s install script
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s-install.sh
    mode: '0755'

# create and enables k3s service (systemctl start k3s)
- name: install k3s server
  ansible.builtin.command:
    cmd: /tmp/k3s-install.sh
  # pass env var to the k3s-install.sh command (server tells the k3s to install k3s in control plane mode (server node))
  environment:
    INSTALL_K3S_EXEC: "server --node-name k3s-server"


- name: fetch kubeconfig to local machine
  ansible.builtin.fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ~/.kube/k3s-coinops.yaml
    flat: true  # saves directly to the path instead of creating nested folders.

- name: generate fixed kubeconfig locally
  ansible.builtin.shell: |
    python3 -c "
    with open('{{ lookup('env', 'HOME') }}/.kube/k3s-coinops-raw.yaml', 'r') as f:
        content = f.read()
    content = content.replace(
        '    server: https://127.0.0.1:6443',
        '    server: https://127.0.0.1:6443\n    tls-server-name: {{ ansible_host }}'
    )
    with open('{{ lookup('env', 'HOME') }}/.kube/k3s-coinops.yaml', 'w') as f:
        f.write(content)
    "
  delegate_to: localhost
  become: false


- name: download helm install script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get-helm-3.sh
    mode: '0755'

# package manager
- name: install helm
  ansible.builtin.command:
    cmd: /tmp/get-helm-3.sh
    creates: /usr/local/bin/helm  # if file already exists - skip 

- name: add headlamp helm repository
  ansible.builtin.command:
    cmd: helm repo add headlamp https://kubernetes-sigs.github.io/headlamp/
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml


- name: update helm repositories
  ansible.builtin.command:
    cmd: helm repo update
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml


- name: install headlamp
  ansible.builtin.command:
    cmd: helm upgrade --install headlamp headlamp/headlamp --namespace kube-system --create-namespace
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml