- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install required packages
  ansible.builtin.apt:
    name:
      - curl
      - ca-certificates
      - gnupg
      - python3
      - python3-pip
    state: present


- name: install python kubernetes library for ansible modules
  ansible.builtin.pip:
    name:
      - kubernetes
      - PyYAML
    state: present
    break_system_packages: true # force ubuntu 24.04 to install system-wide

- name: Set timezone to UTC
  community.general.timezone:
    name: UTC

- name: create app user
  ansible.builtin.user:
    name: rkurdupel
    shell: /bin/bash
    create_home: true # creates /home/rkurdupel (on vm)
    groups: sudo  # add user to sudo group to be able to use sudo (builtin linux group)
    append: true  # don't remove user from existing groups (docker, ubuntu, adm, etc)

- name: set rp_filter to loose mode (required for Tailscale subnet routing)
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: "2"
    state: present
    sysctl_set: true
    reload: true
  loop:
    - net.ipv4.conf.all.rp_filter
    - net.ipv4.conf.default.rp_filter

- name: enable IP forwarding (required for Tailscale subnet router)
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    sysctl_set: true
    reload: true