- name: ensure helm repo is added
  kubernetes.core.helm_repository:
    name: "{{ homepage_chart_repo_name }}"
    repo_url: "{{ homepage_chart_repo_url }}"

- name: render homepage helm values
  ansible.builtin.template:
    src: homepage-values.yml.j2
    dest: "{{ homepage_values_file }}"
    mode: "0600"

  
- name: install or upgrade homepage chart
  kubernetes.core.helm:
    name: "{{ homepage_release_name }}"
    chart_ref: "{{ homepage_chart_repo_name }}/{{ homepage_chart_name }}"
    chart_version: "{{ homepage_chart_version }}"
    release_namespace: "{{ homepage_namespace }}"
    create_namespace: true
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    update_repo_cache: true
    # rendered output of jinja template after (render homepage helm with values), recreates each time in /tmp/ folder
    values_files:
      - "{{ homepage_values_file }}"
    wait: true