# add a helm repo (headlamp) to the local helm config , if addedd - skip
- name: ensure helm repo is added
  kubernetes.core.helm_repository:
    name: "{{ headlamp_chart_repo_name }}"
    repo_url: "{{ headlamp_chart_repo_url }}"

- name: render headlamp helm values
  ansible.builtin.template:
    src: headlamp-values.yml.j2
    dest: "{{ headlamp_values_file }}"
    mode: "0600"

- name: install or upgrade headlamp chart
  kubernetes.core.helm:
    name: "{{ headlamp_release_name }}"
    chart_ref: "{{ headlamp_chart_repo_name }}/{{ headlamp_chart_name }}"
    chart_version: "{{ headlamp_chart_version }}"
    release_namespace: "{{ headlamp_namespace }}"
    create_namespace: true
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    update_repo_cache: true
    values_files:
      - "{{ headlamp_values_file }}"
    wait: true