- name: ensure manifest directory exists
  ansible.builtin.file:
    path: "{{ cert_manager_manifest_dir }}"
    state: directory
    mode: "0700"

- name: add jetstack helm repo
  kubernetes.core_helm_repository:
    name: "{{cert_manager_chart_repo_name}}"
    repo_url: "{{cert_manager_chart_repo_url}}"


- name: install or upgrade cert-manager
  kubernetes.core.helm:
    name: "{{cert_manager_release_name}}"
    chart_ref: "{{ cert_manager_chart_repo_name }}/{{ cert_manager_chart_name }}"
    chart_version: "{{ cert_manager_chart_version }}"
    release_namespace: "{{ cert_manager_namespace }}" # install this release (cert-manager) and put in the cert-manager namespace
    create_namespace: true  # create namespace if does not exist
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    update_repo_cache: true
    wait: true  # after helm install/upgrade block helm until all resources are healthy before returning success
    values:
      crds:
        enabled: true   # crds - custom resource definitions to add (to crds/ folder) from JetStack Github repo like ClusterIssuer

- name: render cloudflare secret manifest
  ansible.builtin.template:
    src: cloudflare-secret.yml.j2
    dest: "{{ cert_manager_manifest_dir }}/cloudflare-secret.yml"
    mode: "0600"
  no_log: true

- name: apply cloudflare secret
  kubernetes.core.k8s:
    state: present
    src: "{{cert_manager_manifest_dir}}/cloudflare-secret.yml"
    kubeconfig: /etc/rancher/k3s/k3s.yaml

- name: render ClusterIssuer manifests
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ cert_manager_manifest_dir }}/{{ item }}"
    mode: "0600"
  loop:
    - issuer-staging.yml
    - issuer-prod.yml

- name: apply ClusterIssuers
  kubenetes.core.k8s:
    state: present
    src: "{{cert_manager_manifest_dir}}/{{item}}"
  loop:
    - issuer-staging.yml
    - issuer-prod.yml
  changed_when: false
 