tailscale_auth_key: "{{lookup('env', 'TAILSCALE_AUTH_KEY')}}"

# name of the current host
# inventory_hostname comes from ansible inventory file (coinops-bastion, coinops-k3s-node-1)
tailscale_hostname: "{{inventory_hostname}}"
# whether the machine acts as a subnet router - a geteway that lets other tailnet devices reach a non-Tailscale network behind it
# only bastion will have :true , because it is the only gateway to reach other vms
tailscale_advertise_routes: false 

# which cidr ranges to advertise if advertise_routes: true
tailscale_routes:
  - 10.10.0.0/16

# shorcut - range of ips that is advertised in (tailscale_advertise_routes) (bastion)
# without advertise routes you cannot reach private ip like 10.10.1.11
# with shortcut request to 10.10.1.11 is seen as advertised by bastion in its range , request is sent to bastion's tailnet ip and bastion forwars it into gcp
# tailscale_accept_routes: false - so not to use tailnet traffic vm to vm but use gcp internal network vpc
# accept routes is turned on when setting up connection to mac to reach private gcp ips from outside
tailscale_accept_routes: false

# the label the machine gets in the tailnet, controlling what acl rules (on tailscale website) apply to it
tailscale_tags:
  - tag:coinops

# replace ssh keys with tailscale-managed auth (lets you `tailscale ssh <node>` without ssh keys)
tailscale_ssh: true