- name: install cert-manager and ClusterIssuers on k3s
  hosts: "{{ansible_play_hosts_all[0]}}" # playbook only triggers hosts (k3s-node) specified in main playbook
  become: true
  roles: 
    - cert-manager