# install basic packages k3s need to run
- name: common setup on all nodes
  hosts: cloud
  become: true
  roles:
    - common

- name: install k3s node
  hosts: k3s_node # # install on k3s_node (vm) group only
  become: true
  roles:
    - k3s-node


