# install basic packages k3s need to run
- name: common setup on all nodes
  hosts: cloud
  become: true
  roles:
    - common

- name: install k3s server
  hosts: k3s_server # install on k3s_server (vm) group only
  become: true
  roles:
    - k3s-server

- name: install k3s worker
  hosts: k3s_worker
  become: true
  roles:
    - k3s-agent